# Generated by Django 3.2.6 on 2021-11-29 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='menu_images')),
                ('recipe', models.TextField(default='')),
                ('ingredient', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.FloatField()),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('count_all', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodayMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakfast', to='kitchen.menu')),
                ('breakfast_other1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakfast1', to='kitchen.menu')),
                ('breakfast_other2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakfast2', to='kitchen.menu')),
                ('breakfast_other3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakfast3', to='kitchen.menu')),
                ('breakfast_other4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breakfast4', to='kitchen.menu')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dinner', to='kitchen.menu')),
                ('dinner_other1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dinner1', to='kitchen.menu')),
                ('dinner_other2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dinner2', to='kitchen.menu')),
                ('dinner_other3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dinner3', to='kitchen.menu')),
                ('dinner_other4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dinner4', to='kitchen.menu')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch', to='kitchen.menu')),
                ('lunch_other1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch1', to='kitchen.menu')),
                ('lunch_other2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch2', to='kitchen.menu')),
                ('lunch_other3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch3', to='kitchen.menu')),
                ('lunch_other4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lunch4', to='kitchen.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('liked', models.BooleanField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='record_images')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_of_record', to='kitchen.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('sex', models.BooleanField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('target_calories', models.IntegerField(null=True)),
                ('api_id', models.IntegerField()),
                ('api_name', models.TextField()),
                ('api_token', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
