# Generated by Django 3.2.7 on 2021-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
