# Generated by Django 3.2.7 on 2021-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='liked',
            field=models.CharField(max_length=32),
        ),
    ]
