# Generated by Django 3.2.7 on 2021-11-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(null=True),
        ),
    ]
