# Generated by Django 3.2.7 on 2021-11-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_preference_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='preference',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.menu'),
        ),
    ]
