# Generated by Django 3.2.7 on 2021-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_record_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='liked',
            field=models.BooleanField(),
        ),
    ]
