# Generated by Django 3.2.7 on 2021-11-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20211108_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
